services:
  postgres:
    image: postgres:16@sha256:33f923b05f64ca54ac4401c01126a6b92afe839a0aa0a52bc5aeb5cc958e5f20
    container_name: cle-postgres
    environment:
      POSTGRES_USER: cle
      POSTGRES_PASSWORD: cle_password
      POSTGRES_DB: cle_db
    ports:
      - "5422:5432"
    volumes:
      - pgdatae:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine@sha256:e7723ff73d963f5cc6d9c4643ea3d989527a402a319239054e9472a7fb9219a2
    container_name: cle-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  pgdatae:



