services:
  postgres:
    image: postgres:16@sha256:f1c3376c26f2609ab9f29f71f824103fe2fcd8ee0346485cb6122a4f93df6f94
    container_name: cle-postgres
    environment:
      POSTGRES_USER: cle
      POSTGRES_PASSWORD: cle_password
      POSTGRES_DB: cle_db
    ports:
      - "5422:5432"
    volumes:
      - pgdatae:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:8-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
    container_name: cle-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  pgdatae:


