services:
  postgres:
    image: postgres:16@sha256:ca0bd484cb98bf4b24eb1010e73fb3fcbd6714d240fbc1a10eea5b7dbecb641d
    container_name: cle-postgres
    environment:
      POSTGRES_USER: cle
      POSTGRES_PASSWORD: cle_password
      POSTGRES_DB: cle_db
    ports:
      - "5422:5432"
    volumes:
      - pgdatae:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:8-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
    container_name: cle-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  pgdatae:


