name: BackendCI Tests

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - "backend/src/**"
      - "backend/tests/**"
      - "backend/Cargo.toml"
      - "backend/Cargo.lock"
      - "backend/migrations/**"

jobs:
  test:
    name: Run Cargo Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Cache Cargo dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}-clippy-${{ hashFiles('backend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}-clippy-
            ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      
      - name: Run cargo fmt
        run: SQLX_OFFLINE=true cargo fmt --all -- --check
      
      - name: Run cargo clippy (zero warnings policy)
        run: SQLX_OFFLINE=true cargo clippy --all-targets --all-features -- -D warnings
      